#!/usr/bin/env python3
"""
run-pipeline.py — autonomous Phase 1 -> 4 runner for the JARVIS content
pipeline. Generates today's batch and writes the articles + meta.json files
under articles/. The downstream qa-and-publish.sh step picks them up and
publishes to Shopify as DRAFTS (PUBLISH_DRAFT=true by default).

Models:
  - Opus 4.7 (claude-opus-4-7) for Phase 1 (strategy) and Phase 4 (gate)
  - Sonnet 4.6 (claude-sonnet-4-6) for Phase 3 (parallel writers)

Usage:
    ANTHROPIC_API_KEY=sk-ant-... python3 scripts/run-pipeline.py [--batch-size 20]

Optional:
    --batch-date YYYY-MM-DD   (default: today UTC)
    --batch-size N            (default: 20)
    --concurrency N           (default: 5; max parallel writers)
    --dry-run                 (run Phase 1 only; print topics, do not write)
    --topics-from FILE        (skip Phase 1, load topics from JSON file)
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import logging
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from agent_runner.phases import (  # noqa: E402
    run_phase1,
    run_phase3_parallel,
    run_phase4_parallel,
    save_article_files,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("run-pipeline")


def _read(path: str) -> str:
    if not os.path.exists(path):
        return ""
    return open(path, encoding="utf-8").read()


def _cleanup_orphan(slug: str) -> None:
    """Remove any stale -final.html / .meta.json from a previous run when this
    slug is rejected today. Prevents republishing of yesterday's pass after
    today's reject."""
    if not slug:
        return
    for path in (
        os.path.join(ROOT, "articles", f"{slug}-final.html"),
        os.path.join(ROOT, "articles", f"{slug}.meta.json"),
    ):
        if os.path.exists(path):
            try:
                os.remove(path)
                log.info("  cleaned orphan %s", os.path.basename(path))
            except OSError:
                pass


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--batch-date", default=dt.date.today().isoformat())
    ap.add_argument("--batch-size", type=int, default=20)
    ap.add_argument("--concurrency", type=int, default=5)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--topics-from", default=None,
                    help="Skip Phase 1; load topics from a JSON file.")
    args = ap.parse_args()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("ERROR: ANTHROPIC_API_KEY not set")

    batch_date = args.batch_date
    log.info("=" * 64)
    log.info("JARVIS pipeline — batch %s, size=%s", batch_date, args.batch_size)
    log.info("=" * 64)

    # ── Phase 1: opportunity engine ────────────────────────────────────────
    if args.topics_from:
        log.info("Loading topics from %s (skipping Phase 1)", args.topics_from)
        plan = json.load(open(args.topics_from))
    else:
        refresh_q = _read(os.path.join(ROOT, "REFRESH-QUEUE.md"))
        comp_q = _read(os.path.join(ROOT, "COMPARISON-QUEUE.md"))
        plan = run_phase1(
            batch_date=batch_date,
            batch_size=args.batch_size,
            refresh_queue_md=refresh_q,
            comparison_queue_md=comp_q,
        )

    topics = plan.get("topics") or []
    log.info("Phase 1 returned %s topics", len(topics))
    for t in topics:
        log.info("  %.1f  [%s]  %s", t.get("priority_score", 0),
                 t.get("format", "standard"), t.get("topic", "")[:60])

    # Persist the batch report for traceability.
    report_path = os.path.join(ROOT, "articles", f"batch-{batch_date}-report.md")
    with open(report_path, "w") as f:
        f.write(f"# Batch report — {batch_date}\n\n")
        f.write(f"Generated by run-pipeline.py (Phase 1 → Phase 4)\n\n")
        f.write("| # | Score | Format | Topic | Slug |\n|---|---:|---|---|---|\n")
        for i, t in enumerate(topics, 1):
            slug = (t.get("refresh_slug") or "").strip() or "(new)"
            f.write(
                f"| {i} | {t.get('priority_score', 0)} | "
                f"{t.get('format', 'standard')} | {t.get('topic', '')[:60]} | "
                f"{slug} |\n"
            )

    if args.dry_run:
        log.info("DRY RUN — stopping after Phase 1.")
        print(json.dumps(plan, ensure_ascii=False, indent=2))
        return

    # ── Phase 3: parallel writers ──────────────────────────────────────────
    articles = run_phase3_parallel(
        topics=topics,
        batch_date=batch_date,
        concurrency=args.concurrency,
    )
    successes = [a for a in articles if not a.get("_failed")]
    log.info("Phase 3 done. %s/%s succeeded", len(successes), len(articles))

    # ── Phase 4: gate (parallel) + persist ─────────────────────────────────
    verdicts = run_phase4_parallel(
        articles=successes,
        batch_date=batch_date,
        concurrency=args.concurrency,
    )
    passed = rejected = 0
    for art, verdict in zip(successes, verdicts):
        slug = art.get("slug", "")
        if verdict is None:
            rejected += 1
            _cleanup_orphan(slug)
            continue
        if verdict["verdict"] == "reject" or verdict["geo_score"] < 70:
            rejected += 1
            log.info("  REJECT %s  score=%s", slug[:40], verdict["geo_score"])
            _cleanup_orphan(slug)
            continue
        save_article_files(article=art, verdict=verdict, batch_date=batch_date)
        passed += 1

    log.info("=" * 64)
    log.info("DONE. passed=%s rejected=%s failed=%s",
             passed, rejected, len(articles) - len(successes))
    log.info("Next: bash scripts/qa-and-publish.sh %s  (publishes as DRAFTS)",
             batch_date)


if __name__ == "__main__":
    main()
